Repository prgrms-aibe-devcourse/AIBE3_Project2_Team1_FE, pull requests merged in 2025-09, with the labels that each got.

#3 [feat] Axios 인스턴스 설정 및 유저 전역 상태 관리 구현
  package-lock.json
  package.json
  src/services/axios.ts
  src/store/useUserStore.ts
Labels: 💡 feature, ⚙️ chore

#5 [feat] 공통 컴포넌트 헤더,푸터 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/layouts/MainLayout.tsx
  src/main.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 💡 feature, ⚙️ chore, 🎨 design

#10 [feat] Proposal 페이지 라우트 추가
  src/App.tsx
  src/features/proposal/index.tsx
  src/pages/Home.tsx
  src/pages/proposal.tsx
  src/router/AppRouter.tsx
  src/router/routes.tsx
Labels: 💡 feature, 🎨 design
