Repository prgrms-aibe-devcourse/AIBE3_Project2_Team1_FE, pull requests merged in 2025-10, with the labels that each got.

#20 [feat] 마이페이지 대시보드 분리 구현
  src/assets/Done.png
  src/assets/Favorite.png
  src/assets/Historical.png
  src/assets/Star Half Empty.png
  src/assets/View.png
  src/features/dashboard/components/EmptyState.tsx
  src/features/dashboard/components/FreelancerCard.tsx
  src/features/dashboard/components/ProjectCard.tsx
  src/features/dashboard/components/RequestCard.tsx
  src/features/dashboard/components/ReviewCard.tsx
  src/features/dashboard/components/TabContent.tsx
  src/features/dashboard/components/TabDashboard.tsx
  src/features/dashboard/index.tsx
  src/features/dashboard/types.ts
  src/features/profile/components/ProfileCard.tsx
  src/features/profile/index.tsx
  src/features/profile/types.ts
  src/pages/Profile.tsx
  src/router/routes.tsx
Labels: 💡 feature, 🎨 design

#23 [feat] 로그인, 회원가입 구현
  .gitignore
  src/components/Header.tsx
  src/features/auth/AuthContext.tsx
  src/features/auth/AuthProvider.tsx
  src/features/auth/LoginPage.tsx
  src/features/auth/auth.ts
  src/features/user/SignUpPage.tsx
  src/features/user/user.ts
  src/main.tsx
  src/router/routes.tsx
  src/services/axios.ts
  src/services/user.ts
  vite.config.ts
Labels: 💡 feature

#26 [fix] 프론트에서 설정한 경로 수정하여 백엔드와 로그인,회원가입,로그아웃 연동
  src/features/auth/auth.ts
  src/features/review/apis/api.ts
  src/services/axios.ts
Labels: 🐛 bug fix

#28 [feat] 관리자 로그인, 대시보드 페이지 구현
  src/features/admin/api.ts
  src/features/admin/pages/AdminDashboardPage.tsx
  src/features/admin/pages/AdminLoginPage.tsx
  src/router/routes.tsx
  src/services/adminAxios.ts
  src/services/user.ts
Labels: 💡 feature
